app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#user_rest:
#    type:     rest
#    resource: AppBundle\Controller\Rest\UserController
#
#location_rest:
#    type:     rest
#    resource: AppBundle\Controller\Rest\LocationController
#
#booking_rest:
#    type:     rest
#    resource: AppBundle\Controller\Rest\BookingController
#
#cars_rest:
#    type:     rest
#    resource: AppBundle\Controller\Rest\CarsController

# fos user routes
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /profile

#fos_user_register:
#    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#    prefix: /register
#
#fos_user_resetting:
#    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#    prefix: /resetting

#fos_user_change_password:
#    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#    prefix: /profile

#sonata user bundle routes
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc/